### ISSUE TITLE
Escan open /opt/malice/UPDATED: no such file or directory when updating

### ISSUE THREAD

**Issue by imerkle** [malice-plugins/escan#1]
```
root@ubuntu-8gb-nyc3-01:~/virustotal# docker run --name=escan malice/escan update
Updating Escan...
open /opt/malice/UPDATED: no such file or directory
```

**Comment by imerkle** [comment]
as i told its happening with with every av not just escan 

```

root@ubuntu-8gb-nyc3-01:/#  docker run --name=fprot malice/fprot update
Updating F-PROT...
 <nil>ading update (%100)
time="2017-09-10T16:57:05Z" level=fatal msg="open /opt/malice/UPDATED: no such file or directory" category=av path= plugin=fprot
```

**Comment by blacktop** [comment]
thank you for bringing this to my attention

I added the update DB feature a long time ago, however, I update by pulling a newer version of the AV docker image personally so that code fell prey to copy-pasta and a lack of CI testing 

I have fixed it in all AVs, they will be slowing building in docker cloud, but please try again and let me know it this has been resolved

**Comment by imerkle** [comment]
Ok . let me know when they have finished building.
Also do i have to again update the whole av `malice plugin update -all` or just do a update `docker run --name=fprot malice/fprot update` ?

**Comment by blacktop** [comment]
`malice plugin update --all` is good because I design my plugins to have updates applied last which leverages the docker image layer caching so that it will only download the updates and not the entire image

**Comment by blacktop** [comment]
the reason for people to run `docker run AV update` is if they want the latest AV sigs daily or hourly etc

I usually only update AVs once a week or two.  That will change once malice is completed as then I will have a service go and update the plugins daily.

**Comment by blacktop** [comment]
I believe all AVs should be fixed now
